spring:
  application:
    name: eureka-config-client-client
  cloud:
    config:
      uri:
        - http://localhost:8082
      fail-fast: false
  config:
    import: configserver:http://localhost:8082
server:
  port: 8083
logging:
  level:
    web: DEBUG
    com.titov: DEBUG