eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true
keycloak:
  realm: tony-realm
  auth-server-url: http://keycloak:8080/auth
  ssl-required: external
  resource: clusid
  credentials:
    secret: bJKmm6jtlz2a7kM7EhdIQ8voe6fSN0LR
  use-resource-role-mappings: true
  bearer-only: true